version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
      - type: bind
        source: server/src
        target: /go/app/src